/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Usuario
 */
public class CRUDEmpaquetadoPalletizado extends javax.swing.JFrame {

    private PantallaPrincipalDigitador pPrincipal;
    /**
     * Creates new form BoletasCosecha
     */
    public CRUDEmpaquetadoPalletizado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackground = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbSubtitulo = new javax.swing.JLabel();
        lbExportadora = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnEliminarEmpaquetado = new javax.swing.JButton();
        btnCargarDatos = new javax.swing.JButton();
        btnNuevoEmpaquetado = new javax.swing.JButton();
        btnEditarEmpaquetado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosPallets = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatosEmpaques = new javax.swing.JTable();
        btnNuevaPallet = new javax.swing.JButton();
        btnEditarPallet = new javax.swing.JButton();
        btnEliminarBoleta1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jpBackground.setBackground(new java.awt.Color(255, 255, 204));
        jpBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("LOS 3 PATITOS");
        jpBackground.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        lbSubtitulo.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        lbSubtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbSubtitulo.setText("Empaquetado y Palletizado");
        jpBackground.add(lbSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, 20));

        lbExportadora.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        lbExportadora.setForeground(new java.awt.Color(0, 0, 0));
        lbExportadora.setText("Exportadora");
        jpBackground.add(lbExportadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jpBackground.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 10, 120, -1));

        btnEliminarEmpaquetado.setBackground(new java.awt.Color(255, 204, 204));
        btnEliminarEmpaquetado.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnEliminarEmpaquetado.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarEmpaquetado.setText("Eliminar Empaquetado");
        btnEliminarEmpaquetado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpaquetadoActionPerformed(evt);
            }
        });
        jpBackground.add(btnEliminarEmpaquetado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 200, 30));

        btnCargarDatos.setBackground(new java.awt.Color(204, 204, 0));
        btnCargarDatos.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnCargarDatos.setForeground(new java.awt.Color(0, 0, 0));
        btnCargarDatos.setText("Cargar Datos");
        jpBackground.add(btnCargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 30));

        btnNuevoEmpaquetado.setBackground(new java.awt.Color(204, 255, 204));
        btnNuevoEmpaquetado.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnNuevoEmpaquetado.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevoEmpaquetado.setText("Nuevo Empaquetado");
        jpBackground.add(btnNuevoEmpaquetado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, 30));

        btnEditarEmpaquetado.setBackground(new java.awt.Color(204, 255, 255));
        btnEditarEmpaquetado.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnEditarEmpaquetado.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarEmpaquetado.setText("Editar Empaquetado");
        jpBackground.add(btnEditarEmpaquetado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 30));

        tblDatosPallets.setBackground(new java.awt.Color(255, 255, 255));
        tblDatosPallets.setForeground(new java.awt.Color(0, 0, 0));
        tblDatosPallets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatosPallets);

        jpBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 470, 390));

        tblDatosEmpaques.setBackground(new java.awt.Color(255, 255, 255));
        tblDatosEmpaques.setForeground(new java.awt.Color(0, 0, 0));
        tblDatosEmpaques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDatosEmpaques);

        jpBackground.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 480, 390));

        btnNuevaPallet.setBackground(new java.awt.Color(204, 255, 204));
        btnNuevaPallet.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnNuevaPallet.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevaPallet.setText("Nuevo Pallet");
        jpBackground.add(btnNuevaPallet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 30));

        btnEditarPallet.setBackground(new java.awt.Color(204, 255, 255));
        btnEditarPallet.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnEditarPallet.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarPallet.setText("Editar Pallet");
        jpBackground.add(btnEditarPallet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, 30));

        btnEliminarBoleta1.setBackground(new java.awt.Color(255, 204, 204));
        btnEliminarBoleta1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnEliminarBoleta1.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarBoleta1.setText("Eliminar Pallet");
        jpBackground.add(btnEliminarBoleta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1273, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        pPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarEmpaquetadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpaquetadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEmpaquetadoActionPerformed

    public void setPrincipal(PantallaPrincipalDigitador pPrincipal){
        this.pPrincipal = pPrincipal;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDEmpaquetadoPalletizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDEmpaquetadoPalletizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDEmpaquetadoPalletizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDEmpaquetadoPalletizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDEmpaquetadoPalletizado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnEditarEmpaquetado;
    private javax.swing.JButton btnEditarPallet;
    private javax.swing.JButton btnEliminarBoleta1;
    private javax.swing.JButton btnEliminarEmpaquetado;
    private javax.swing.JButton btnNuevaPallet;
    private javax.swing.JButton btnNuevoEmpaquetado;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpBackground;
    private javax.swing.JLabel lbExportadora;
    private javax.swing.JLabel lbSubtitulo;
    private javax.swing.JLabel lbTitulo;
    public javax.swing.JTable tblDatosEmpaques;
    public javax.swing.JTable tblDatosPallets;
    // End of variables declaration//GEN-END:variables
}
