/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import datos.BoletasDB;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import logica.BoletaCosecha;

/**
 *
 * @author Usuario
 */
public class CRUDBoletasCosecha extends javax.swing.JFrame {

    private PantallaPrincipalDigitador pPrincipal;
    
    /**
     * Creates new form BoletasCosecha
     */
    public CRUDBoletasCosecha() {
        initComponents();
        cargarDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackground = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbSubtitulo = new javax.swing.JLabel();
        lbExportadora = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnEliminarBoleta = new javax.swing.JButton();
        btnCargarDatos = new javax.swing.JButton();
        btnNuevaBoleta = new javax.swing.JButton();
        btnEditarBoleta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jpBackground.setBackground(new java.awt.Color(255, 255, 204));
        jpBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("LOS 3 PATITOS");
        jpBackground.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        lbSubtitulo.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        lbSubtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbSubtitulo.setText("Boleta de Cosecha");
        jpBackground.add(lbSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, 20));

        lbExportadora.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        lbExportadora.setForeground(new java.awt.Color(0, 0, 0));
        lbExportadora.setText("Exportadora");
        jpBackground.add(lbExportadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jpBackground.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 10, 120, -1));

        btnEliminarBoleta.setBackground(new java.awt.Color(255, 204, 204));
        btnEliminarBoleta.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnEliminarBoleta.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarBoleta.setText("Eliminar boleta");
        btnEliminarBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBoletaActionPerformed(evt);
            }
        });
        jpBackground.add(btnEliminarBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, 30));

        btnCargarDatos.setBackground(new java.awt.Color(204, 204, 0));
        btnCargarDatos.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnCargarDatos.setForeground(new java.awt.Color(0, 0, 0));
        btnCargarDatos.setText("Cargar Datos");
        jpBackground.add(btnCargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 30));

        btnNuevaBoleta.setBackground(new java.awt.Color(204, 255, 204));
        btnNuevaBoleta.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnNuevaBoleta.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevaBoleta.setText("Nueva boleta");
        btnNuevaBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaBoletaActionPerformed(evt);
            }
        });
        jpBackground.add(btnNuevaBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 30));

        btnEditarBoleta.setBackground(new java.awt.Color(204, 255, 255));
        btnEditarBoleta.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnEditarBoleta.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarBoleta.setText("Editar boleta");
        btnEditarBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarBoletaActionPerformed(evt);
            }
        });
        jpBackground.add(btnEditarBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, 30));

        tblDatos.setBackground(new java.awt.Color(255, 255, 255));
        tblDatos.setForeground(new java.awt.Color(0, 0, 0));
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jpBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 1070, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1273, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        pPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnNuevaBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaBoletaActionPerformed
        BoletasDB gestor = new BoletasDB();
        List<Map<Integer, String>> proveedores = new ArrayList<>();
        List<Map<Integer, String>> fincas = new ArrayList<>();
        List<Map<Integer, String>> tipos = new ArrayList<>();
        
        proveedores = gestor.obtenerProveedores();
        fincas = gestor.obtenerFincas();
        tipos = gestor.obtenerTipos();
        
        POPBoletas pGestion = new POPBoletas();
        pGestion.setComboBox(proveedores, fincas, tipos);
        pGestion.setCrud(this);
        pGestion.setLocationRelativeTo(null);
        pGestion.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnNuevaBoletaActionPerformed

    private void btnEditarBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarBoletaActionPerformed
        BoletasDB gestor = new BoletasDB();
        BoletaCosecha boleta = gestor.seleccionarBoleta(tblDatos);
        
        List<Map<Integer, String>> proveedores = new ArrayList<>();
        List<Map<Integer, String>> fincas = new ArrayList<>();
        List<Map<Integer, String>> tipos = new ArrayList<>();
        
        proveedores = gestor.obtenerProveedores();
        fincas = gestor.obtenerFincas();
        tipos = gestor.obtenerTipos();
        if (boleta != null){
            POPBoletas pGestion = new POPBoletas();
            pGestion.setComboBox(proveedores, fincas, tipos);
            pGestion.setEditando(true, boleta);
            pGestion.setCrud(this);
            pGestion.setLocationRelativeTo(null);
            pGestion.setVisible(true);
            this.setEnabled(false);
        }
    }//GEN-LAST:event_btnEditarBoletaActionPerformed

    private void btnEliminarBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBoletaActionPerformed
        BoletasDB gestor = new BoletasDB();
        BoletaCosecha boleta = gestor.seleccionarBoleta(tblDatos);
        if (boleta != null){
            gestor.eliminarBoleta(boleta.getId());
            cargarDatosTabla();
        }
    }//GEN-LAST:event_btnEliminarBoletaActionPerformed
  
    public void cargarDatosTabla(){
        BoletasDB gestor = new BoletasDB();
        gestor.cargarBoletas(tblDatos);
    }
    
    public void setPrincipal(PantallaPrincipalDigitador pPrincipal){
        this.pPrincipal = pPrincipal;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDBoletasCosecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDBoletasCosecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDBoletasCosecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDBoletasCosecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDBoletasCosecha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnEditarBoleta;
    private javax.swing.JButton btnEliminarBoleta;
    private javax.swing.JButton btnNuevaBoleta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpBackground;
    private javax.swing.JLabel lbExportadora;
    private javax.swing.JLabel lbSubtitulo;
    private javax.swing.JLabel lbTitulo;
    public javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
