package interfaces;

import datos.UsuariosDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Usuario;

public class Login extends javax.swing.JFrame {
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroudPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lbPassword = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroudPanel.setBackground(new java.awt.Color(255, 255, 204));
        backgroudPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(102, 102, 0));

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("LOGIN");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle)
                .addGap(168, 168, 168))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbTitle)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        backgroudPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setToolTipText("");
        txtUsuario.setName(""); // NOI18N
        txtUsuario.setPreferredSize(new java.awt.Dimension(64, 30));
        backgroudPanel.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 220, -1));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.setToolTipText("");
        txtPassword.setPreferredSize(new java.awt.Dimension(64, 30));
        backgroudPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 220, -1));

        lbPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(0, 0, 0));
        lbPassword.setText("Contraseña");
        backgroudPanel.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        lbUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lbUsuario.setText("Usuario");
        backgroudPanel.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        btnIniciarSesion.setBackground(new java.awt.Color(204, 204, 0));
        btnIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        backgroudPanel.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 220, -1));

        getContentPane().add(backgroudPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String username = txtUsuario.getText();
        String password = txtPassword.getText();
        
        if (username.isEmpty() || username.isBlank() || password.isEmpty() || password.isBlank()) {
            JOptionPane.showMessageDialog(this, "Verifique que ninguna casilla esté en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
            Usuario usuario = UsuariosDB.verificarUsuario(username, password);
                if (usuario == null){
                    JOptionPane.showMessageDialog(this, "Datos erroneos o usuario no existente", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    txtUsuario.setText(null);
                    txtPassword.setText(null);
                    if (usuario.getAdmin()){
                       JOptionPane.showMessageDialog(this, "Sesión iniciada correctamente, Bienvenido administrador", "Succesful", JOptionPane.INFORMATION_MESSAGE);
                       PantallaPrincipalAdmin pPrincipal = new PantallaPrincipalAdmin();
                       pPrincipal.setLogin(this);
                       pPrincipal.setLocationRelativeTo(null);
                       pPrincipal.setVisible(true);
                       this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Sesión iniciada correctamente, Bienvenido digitador", "Succesful", JOptionPane.INFORMATION_MESSAGE);
                       PantallaPrincipalDigitador pPrincipal = new PantallaPrincipalDigitador();
                       pPrincipal.setLogin(this);
                       pPrincipal.setLocationRelativeTo(null);
                       pPrincipal.setVisible(true);
                       this.setVisible(false);
                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroudPanel;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
