package interfaces;


public class PantallaPrincipalDigitador extends javax.swing.JFrame {
    
    private Login login;
    private boolean admin = false;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipalDigitador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackground = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbSubtitulo = new javax.swing.JLabel();
        lbExportadora = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnInmersión = new javax.swing.JButton();
        btnBoletas = new javax.swing.JButton();
        btnEmpaque = new javax.swing.JButton();
        btnPaginaAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpBackground.setBackground(new java.awt.Color(255, 255, 204));
        jpBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("LOS 3 PATITOS");
        jpBackground.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        lbSubtitulo.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        lbSubtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbSubtitulo.setText("Sistema principal");
        jpBackground.add(lbSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, 20));

        lbExportadora.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        lbExportadora.setForeground(new java.awt.Color(0, 0, 0));
        lbExportadora.setText("Exportadora");
        jpBackground.add(lbExportadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        btnLogout.setBackground(new java.awt.Color(255, 204, 153));
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jpBackground.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(255, 204, 204));
        btnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jpBackground.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        btnReportes.setBackground(new java.awt.Color(204, 204, 0));
        btnReportes.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(0, 0, 0));
        btnReportes.setText("Reportes");
        btnReportes.setToolTipText("");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jpBackground.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 260, 110));

        btnInmersión.setBackground(new java.awt.Color(204, 204, 0));
        btnInmersión.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnInmersión.setForeground(new java.awt.Color(0, 0, 0));
        btnInmersión.setText("Inmersiones");
        btnInmersión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInmersiónActionPerformed(evt);
            }
        });
        jpBackground.add(btnInmersión, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 260, 110));

        btnBoletas.setBackground(new java.awt.Color(204, 204, 0));
        btnBoletas.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnBoletas.setForeground(new java.awt.Color(0, 0, 0));
        btnBoletas.setText("Boletas de Cosecha");
        btnBoletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletasActionPerformed(evt);
            }
        });
        jpBackground.add(btnBoletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 260, 110));

        btnEmpaque.setBackground(new java.awt.Color(204, 204, 0));
        btnEmpaque.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnEmpaque.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpaque.setText("Empaque y Palletizado");
        btnEmpaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpaqueActionPerformed(evt);
            }
        });
        jpBackground.add(btnEmpaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 260, 110));

        btnPaginaAdmin.setBackground(new java.awt.Color(204, 204, 0));
        btnPaginaAdmin.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnPaginaAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btnPaginaAdmin.setText("Perfil Admin");
        btnPaginaAdmin.setToolTipText("");
        btnPaginaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaAdminActionPerformed(evt);
            }
        });
        jpBackground.add(btnPaginaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 160, 50));

        getContentPane().add(jpBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBoletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletasActionPerformed
        CRUDBoletasCosecha pBoletas = new CRUDBoletasCosecha();
        pBoletas.setPrincipal(this);
        pBoletas.setLocationRelativeTo(null);
        pBoletas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBoletasActionPerformed

    private void btnInmersiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInmersiónActionPerformed
        CRUDInmersiones pInmersiones = new CRUDInmersiones();
        pInmersiones.setPrincipal(this);
        pInmersiones.setLocationRelativeTo(null);
        pInmersiones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInmersiónActionPerformed

    private void btnEmpaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpaqueActionPerformed
        CRUDEmpaquetadoPalletizado pEmpaquetado = new CRUDEmpaquetadoPalletizado();
        pEmpaquetado.setPrincipal(this);
        pEmpaquetado.setLocationRelativeTo(null);
        pEmpaquetado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpaqueActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        /*CRUDBoletasCosecha pBoletas = new CRUDBoletasCosecha();
        pBoletas.setPrincipal(this);
        pBoletas.setLocationRelativeTo(null);
        pBoletas.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnPaginaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaAdminActionPerformed
        PantallaPrincipalAdmin pAdmin = new PantallaPrincipalAdmin();
        pAdmin.setLogin(this.login);
        pAdmin.setLocationRelativeTo(null);
        pAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPaginaAdminActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.btnPaginaAdmin.setVisible(admin);
    }//GEN-LAST:event_formWindowOpened
    
    public void setAdmin(boolean admin){
        this.admin = admin;
    }
    public void setLogin(Login login){
        this.login = login;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalDigitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalDigitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalDigitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalDigitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipalDigitador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoletas;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEmpaque;
    private javax.swing.JButton btnInmersión;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPaginaAdmin;
    private javax.swing.JButton btnReportes;
    private javax.swing.JPanel jpBackground;
    private javax.swing.JLabel lbExportadora;
    private javax.swing.JLabel lbSubtitulo;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
