/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import datos.BoletasDB;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import logica.BoletaCosecha;

/**
 *
 * @author Usuario
 */
public class POPBoletas extends javax.swing.JFrame {

    private CRUDBoletasCosecha crud;
    private boolean editando = false;
    private BoletaCosecha boleta;
    private List<Map<Integer, String>> proveedores = new ArrayList<>();
    private List<Map<Integer, String>> fincas = new ArrayList<>();
    private List<Map<Integer, String>> tipos = new ArrayList<>();
    
    public POPBoletas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbLote = new javax.swing.JLabel();
        lbProveedor = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        txtPlacaCamion = new javax.swing.JTextField();
        lbBinB = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtFrutasBinB = new javax.swing.JTextField();
        lbFinca = new javax.swing.JLabel();
        cbFincas = new javax.swing.JComboBox<>();
        cbProveedores = new javax.swing.JComboBox<>();
        lbBloque = new javax.swing.JLabel();
        lbBinA = new javax.swing.JLabel();
        lbFrutasBinA = new javax.swing.JLabel();
        lbFrutasBinB = new javax.swing.JLabel();
        txtNumeroBinB = new javax.swing.JTextField();
        txtFrutasBinA = new javax.swing.JTextField();
        txtNumeroBinA = new javax.swing.JTextField();
        lbPlacaCamion = new javax.swing.JLabel();
        lbFrutasBinB1 = new javax.swing.JLabel();
        cbTipos = new javax.swing.JComboBox<>();
        txtBloque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("Gestión de Proveedor");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lbLote.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbLote.setForeground(new java.awt.Color(0, 0, 0));
        lbLote.setText("Lote");
        jPanel1.add(lbLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        lbProveedor.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbProveedor.setForeground(new java.awt.Color(0, 0, 0));
        lbProveedor.setText("Proveedor");
        jPanel1.add(lbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        txtLote.setForeground(new java.awt.Color(0, 0, 0));
        txtLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLoteKeyTyped(evt);
            }
        });
        jPanel1.add(txtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, -1));

        txtPlacaCamion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPlacaCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 140, -1));

        lbBinB.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbBinB.setForeground(new java.awt.Color(0, 0, 0));
        lbBinB.setText("Número Bin B");
        jPanel1.add(lbBinB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, 20));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 0));
        btnCancelar.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        txtFrutasBinB.setForeground(new java.awt.Color(0, 0, 0));
        txtFrutasBinB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrutasBinBKeyTyped(evt);
            }
        });
        jPanel1.add(txtFrutasBinB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 140, -1));

        lbFinca.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbFinca.setForeground(new java.awt.Color(0, 0, 0));
        lbFinca.setText("Finca");
        jPanel1.add(lbFinca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, 20));

        jPanel1.add(cbFincas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 140, -1));

        jPanel1.add(cbProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 140, -1));

        lbBloque.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbBloque.setForeground(new java.awt.Color(0, 0, 0));
        lbBloque.setText("Bloque");
        jPanel1.add(lbBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, 20));

        lbBinA.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbBinA.setForeground(new java.awt.Color(0, 0, 0));
        lbBinA.setText("Número Bin A");
        jPanel1.add(lbBinA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        lbFrutasBinA.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbFrutasBinA.setForeground(new java.awt.Color(0, 0, 0));
        lbFrutasBinA.setText("Cantidad de Frutas");
        jPanel1.add(lbFrutasBinA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        lbFrutasBinB.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbFrutasBinB.setForeground(new java.awt.Color(0, 0, 0));
        lbFrutasBinB.setText("Cantidad de Frutas");
        jPanel1.add(lbFrutasBinB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, 20));

        txtNumeroBinB.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtNumeroBinB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 140, -1));

        txtFrutasBinA.setForeground(new java.awt.Color(0, 0, 0));
        txtFrutasBinA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrutasBinAKeyTyped(evt);
            }
        });
        jPanel1.add(txtFrutasBinA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, -1));

        txtNumeroBinA.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtNumeroBinA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, -1));

        lbPlacaCamion.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbPlacaCamion.setForeground(new java.awt.Color(0, 0, 0));
        lbPlacaCamion.setText("Placa del Camión");
        jPanel1.add(lbPlacaCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        lbFrutasBinB1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbFrutasBinB1.setForeground(new java.awt.Color(0, 0, 0));
        lbFrutasBinB1.setText("Tipo de Fruto");
        jPanel1.add(lbFrutasBinB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, 20));

        jPanel1.add(cbTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 140, -1));

        txtBloque.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        crud.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String lote = txtLote.getText();
        String bloque = txtBloque.getText();
        String numeroBinA = txtNumeroBinA.getText();
        String numeroBinB = txtNumeroBinB.getText();
        int cantidadBinA = Integer.parseInt(txtFrutasBinA.getText());
        int cantidadBinB = Integer.parseInt(txtFrutasBinB.getText());
        String placaCamion = txtPlacaCamion.getText();
        
        int selectedProveedor = cbProveedores.getSelectedIndex();
        int selectedFinca = cbFincas.getSelectedIndex();
        int selectedTipo = cbTipos.getSelectedIndex();
        
        if (lote.isEmpty() || bloque.isEmpty() || numeroBinA.isEmpty() || numeroBinB.isEmpty() || Integer.toString(cantidadBinA).isEmpty() || Integer.toString(cantidadBinB).isEmpty() || placaCamion.isEmpty()){
            JOptionPane.showMessageDialog(this, "Verifique ningún dato esté en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            BoletasDB gestor = new BoletasDB();
            
            Map<Integer, String> proveedor = this.proveedores.get(selectedProveedor);
            Map<Integer, String> finca = this.fincas.get(selectedFinca);
            Map<Integer, String> tipo = this.tipos.get(selectedTipo);
            
            int id_proveedor = proveedor.keySet().iterator().next();
            int id_finca = finca.keySet().iterator().next();
            int id_tipoFruto = tipo.keySet().iterator().next();
            
            System.out.println(selectedProveedor);
            System.out.println(selectedFinca);
            System.out.println(selectedTipo);
            
            System.out.println(id_proveedor);
            System.out.println(id_finca);
            System.out.println(id_tipoFruto);
            
            String fecha;
            SimpleDateFormat formatter = new SimpleDateFormat("HH:mm dd/MM/yyyy");
            fecha = formatter.format(new Date());
            
            if (editando){
                BoletaCosecha boletaEdit = new BoletaCosecha(this.boleta.getId(), id_proveedor, id_finca, lote, bloque, numeroBinA, cantidadBinA, numeroBinB, cantidadBinB, placaCamion, id_tipoFruto);
                gestor.editarBoleta(boletaEdit);
            } else {
                BoletaCosecha boleta = new BoletaCosecha(0, id_proveedor, id_finca, lote, bloque, numeroBinA, cantidadBinA, numeroBinB, cantidadBinB, placaCamion, id_tipoFruto);
                gestor.agregarBoleta(boleta);
                gestor.editarConsecutivoBoleta();
            }
        }
        
        crud.cargarDatosTabla();
        crud.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtLoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoteKeyTyped
        // IMPIDE DIGITAR OTRA COSA QUE NO SEAN NUMEROS
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros)
        {
            evt.consume();
        }

        if (txtLote.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtLoteKeyTyped

    private void txtFrutasBinBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrutasBinBKeyTyped
        // IMPIDE DIGITAR OTRA COSA QUE NO SEAN NUMEROS
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros)
        {
            evt.consume();
        }

        if (txtLote.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFrutasBinBKeyTyped

    private void txtFrutasBinAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrutasBinAKeyTyped
        // IMPIDE DIGITAR OTRA COSA QUE NO SEAN NUMEROS
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros)
        {
            evt.consume();
        }

        if (txtLote.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFrutasBinAKeyTyped

    public void setComboBox(List<Map<Integer, String>> proveedores, List<Map<Integer, String>> fincas, List<Map<Integer, String>> tipos){
        this.proveedores = proveedores;
        this.fincas = fincas;
        this.tipos = tipos;
        
        cbProveedores.removeAllItems();
        cbFincas.removeAllItems();
        cbTipos.removeAllItems();
        
        for(int i = 0; i < proveedores.size(); i++){
            Map<Integer, String> proveedor = proveedores.get(i);
            for (Map.Entry<Integer, String> entry : proveedor.entrySet()) {
                cbProveedores.addItem(entry.getValue());
            }
        }
        
        for(int i = 0; i < fincas.size(); i++){
            Map<Integer, String> finca = fincas.get(i);
            for (Map.Entry<Integer, String> entry : finca.entrySet()) {
                cbFincas.addItem(entry.getValue());
            }
        }
        
        for(int i = 0; i < tipos.size(); i++){
            Map<Integer, String> tipo = tipos.get(i);
            for (Map.Entry<Integer, String> entry : tipo.entrySet()) {
                cbTipos.addItem(entry.getValue());
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public void setCrud(CRUDBoletasCosecha crud){
        
        this.crud = crud;
    }
    
    public void setEditando(boolean editando, BoletaCosecha boleta){
        if (boleta != null){
            this.boleta = boleta;
            txtLote.setText(boleta.getLote());
            txtBloque.setText(boleta.getBloque());
            txtNumeroBinA.setText(boleta.getNumeroBinA());
            txtNumeroBinB.setText(boleta.getNumeroBinB());
            txtFrutasBinA.setText(String.valueOf(boleta.getCantidadFrutaBinA()));
            txtFrutasBinB.setText(String.valueOf(boleta.getCantidadFrutaBinB()));
            txtPlacaCamion.setText(boleta.getPlacaCamion());
        }
        this.editando = editando;
    }
    
    /*public void setEditando(boolean editando, Proveedor proveedor){
        if (proveedor != null) {
            this.proveedor = proveedor;
            txtProveedor.setText(proveedor.getNombre());
            txtPlacaCamion.setText(proveedor.getEncargado());
            txtLote.setText(String.valueOf(proveedor.getTelefono()));
            txtCorreo.setText(proveedor.getCorreo());
        }
        this.editando = editando;
    }*/
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POPBoletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POPBoletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POPBoletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POPBoletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POPBoletas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbFincas;
    private javax.swing.JComboBox<String> cbProveedores;
    private javax.swing.JComboBox<String> cbTipos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBinA;
    private javax.swing.JLabel lbBinB;
    private javax.swing.JLabel lbBloque;
    private javax.swing.JLabel lbFinca;
    private javax.swing.JLabel lbFrutasBinA;
    private javax.swing.JLabel lbFrutasBinB;
    private javax.swing.JLabel lbFrutasBinB1;
    private javax.swing.JLabel lbLote;
    private javax.swing.JLabel lbPlacaCamion;
    private javax.swing.JLabel lbProveedor;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtBloque;
    private javax.swing.JTextField txtFrutasBinA;
    private javax.swing.JTextField txtFrutasBinB;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNumeroBinA;
    private javax.swing.JTextField txtNumeroBinB;
    private javax.swing.JTextField txtPlacaCamion;
    // End of variables declaration//GEN-END:variables
}
