/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import datos.FincasDB;
import javax.swing.JOptionPane;
import logica.Finca;

/**
 *
 * @author Usuario
 */
public class POPFincas extends javax.swing.JFrame {

    private CRUDFincas crud;
    private boolean editando = false;
    private Finca finca;
    
    public POPFincas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbUbicacion = new javax.swing.JLabel();
        lbFinca = new javax.swing.JLabel();
        txtFinca = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        lbNombreProveedor = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtProveedor = new javax.swing.JTextField();
        lbProveedor1 = new javax.swing.JLabel();
        btnBuscarProveedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("Gestión de Finca");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lbUbicacion.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        lbUbicacion.setText("Ubicación");
        jPanel1.add(lbUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        lbFinca.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbFinca.setForeground(new java.awt.Color(0, 0, 0));
        lbFinca.setText("Nombre de la finca");
        jPanel1.add(lbFinca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        txtFinca.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtFinca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 330, -1));

        txtUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 330, -1));

        lbNombreProveedor.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbNombreProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 0));
        btnCancelar.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 100, 30));

        txtProveedor.setForeground(new java.awt.Color(0, 0, 0));
        txtProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProveedorKeyTyped(evt);
            }
        });
        jPanel1.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 330, -1));

        lbProveedor1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbProveedor1.setForeground(new java.awt.Color(0, 0, 0));
        lbProveedor1.setText("ID del Proveedor");
        jPanel1.add(lbProveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        btnBuscarProveedor.setBackground(new java.awt.Color(204, 204, 0));
        btnBuscarProveedor.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        btnBuscarProveedor.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarProveedor.setText("Buscar Proveedor");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        crud.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre = txtFinca.getText();
        String ubicacion = txtUbicacion.getText();
        String id_proveedor = txtProveedor.getText();

        if (nombre.isEmpty() || ubicacion.isEmpty() || id_proveedor.isEmpty()){
            JOptionPane.showMessageDialog(this, "Verifique ningún dato esté en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            FincasDB gestor = new FincasDB();
            if (editando){
                gestor.editarFinca(this.finca.getId(), nombre, ubicacion, Integer.parseInt(id_proveedor));
            } else {
                gestor.agregarFinca(nombre, ubicacion, Integer.parseInt(id_proveedor));
            }
            
            crud.cargarDatosTabla();
            crud.setEnabled(true);
            this.dispose();
        }  
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros)
        {
            evt.consume();
        }

        if (txtProveedor.getText().trim().length() == 10) {
            evt.consume();
        }   
    }//GEN-LAST:event_txtProveedorKeyTyped

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        FincasDB gestor = new FincasDB();
        String nombre;
        nombre = gestor.obtenerNombreProveedor(Integer.parseInt(txtProveedor.getText()));
        lbNombreProveedor.setText(nombre);
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public void setCrud(CRUDFincas crud){
        this.crud = crud;
    }
    
    public void setEditando(boolean editando, Finca finca){
        if (finca != null) {
            this.finca = finca;
            txtFinca.setText(finca.getNombre());
            txtUbicacion.setText(finca.getUbicacion());
            txtProveedor.setText(String.valueOf(finca.getId_proveedor()));
        }
        this.editando = editando;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POPFincas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POPFincas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POPFincas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POPFincas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POPFincas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFinca;
    private javax.swing.JLabel lbNombreProveedor;
    private javax.swing.JLabel lbProveedor1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUbicacion;
    private javax.swing.JTextField txtFinca;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
