/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import datos.ProveedoresDB;
import javax.swing.JOptionPane;
import logica.Proveedor;

/**
 *
 * @author Usuario
 */
public class POPProveedores extends javax.swing.JFrame {

    private CRUDProveedores crud;
    private boolean editando = false;
    private Proveedor proveedor;
    
    public POPProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbEncargado = new javax.swing.JLabel();
        lbProveedor = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        txtEncargado = new javax.swing.JTextField();
        lbTelefono = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lbCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("Gestión de Proveedor");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lbEncargado.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbEncargado.setForeground(new java.awt.Color(0, 0, 0));
        lbEncargado.setText("Nombre del encargado");
        jPanel1.add(lbEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        lbProveedor.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbProveedor.setForeground(new java.awt.Color(0, 0, 0));
        lbProveedor.setText("Nombre del proveedor");
        jPanel1.add(lbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 330, -1));

        txtProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 330, -1));

        txtEncargado.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 330, -1));

        lbTelefono.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbTelefono.setForeground(new java.awt.Color(0, 0, 0));
        lbTelefono.setText("Telefono");
        jPanel1.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 0));
        btnCancelar.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        lbCorreo.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lbCorreo.setText("Correo");
        jPanel1.add(lbCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 330, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        crud.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre = txtProveedor.getText();
        String encargado = txtEncargado.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        
        if (nombre.isEmpty() || encargado.isEmpty() || telefono.isEmpty() || correo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Verifique ningún dato esté en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ProveedoresDB gestor = new ProveedoresDB();
            if (editando){
                gestor.editarProveedor(this.proveedor.getId(), nombre, encargado, telefono, correo);
            } else {
                gestor.agregarProveedor(nombre, encargado, telefono, correo);
            }
        }
        
        crud.cargarDatosTabla();
        crud.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // IMPIDE DIGITAR OTRA COSA QUE NO SEAN NUMEROS
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros)
        {
            evt.consume();
        }

        if (txtTelefono.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public void setCrud(CRUDProveedores crud){
        this.crud = crud;
    }
    
    public void setEditando(boolean editando, Proveedor proveedor){
        if (proveedor != null) {
            this.proveedor = proveedor;
            txtProveedor.setText(proveedor.getNombre());
            txtEncargado.setText(proveedor.getEncargado());
            txtTelefono.setText(String.valueOf(proveedor.getTelefono()));
            txtCorreo.setText(proveedor.getCorreo());
        }
        this.editando = editando;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POPProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POPProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POPProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POPProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POPProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbEncargado;
    private javax.swing.JLabel lbProveedor;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEncargado;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
