/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import datos.UsuariosDB;
import javax.swing.JOptionPane;
import logica.Usuario;

/**
 *
 * @author Usuario
 */
public class POPUsuarios extends javax.swing.JFrame {

    private CRUDUsuarios crud;
    private boolean editando = false;
    private Usuario usuario;
    
    public POPUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbAdmin = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lbPasswordRep = new javax.swing.JLabel();
        checkAdmin = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbAdmin.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbAdmin.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmin.setText("Otorgar administrador");
        jPanel1.add(lbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        lbTitulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("Gestión de Usuario");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lbPassword.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(0, 0, 0));
        lbPassword.setText("Contraseña");
        jPanel1.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        lbUsuario.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lbUsuario.setText("Usuario");
        jPanel1.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, -1));

        lbPasswordRep.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbPasswordRep.setForeground(new java.awt.Color(0, 0, 0));
        lbPasswordRep.setText("Confirmar Contraseña");
        jPanel1.add(lbPasswordRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));
        jPanel1.add(checkAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 30, 30));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 0));
        btnCancelar.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        txtConfirmPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtConfirmPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtConfirmPassword.setToolTipText("");
        txtConfirmPassword.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel1.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, 20));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.setToolTipText("");
        txtPassword.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 220, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        crud.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String username = txtUser.getText();
        String password = txtPassword.getText();
        String confirmPassword = txtConfirmPassword.getText();
        boolean admin = checkAdmin.isSelected();
        
        if (username.isEmpty() || username.isBlank() || password.isBlank() || password.isEmpty() || confirmPassword.isBlank() || confirmPassword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Verifique ningún dato esté en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!password.equals(confirmPassword)){
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            UsuariosDB gestor = new UsuariosDB();
            if (editando){
                gestor.editarUsuario(this.usuario.getId(), username, password, admin);
            } else {
                gestor.agregarUsuario(username, password, admin);
            }
            
            crud.cargarDatosTabla();
            crud.setEnabled(true);
            this.dispose();
        }   
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setEditando(boolean editando, Usuario usuario){ 
        if (usuario != null) {
            this.usuario = usuario;
            txtUser.setText(usuario.getUsername());
            txtPassword.setText(usuario.getPassword());
            if (usuario.getAdmin()) {
                checkAdmin.setSelected(true);
            } else {
                checkAdmin.setSelected(false);
            }
        }
        this.editando = editando;
    }
    
    public void setCrud(CRUDUsuarios crud){
        this.crud = crud;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POPUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POPUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POPUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POPUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POPUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox checkAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAdmin;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPasswordRep;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
