/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import datos.VariedadesDB;
import javax.swing.JOptionPane;
import logica.VariedadFruto;

/**
 *
 * @author Usuario
 */
public class POPVariedadFruta extends javax.swing.JFrame {

    private CRUDVariedadFruta crud;
    private boolean editando = false;
    private VariedadFruto variedad;
    
    public POPVariedadFruta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbCaracteristicas = new javax.swing.JLabel();
        lbVariedad = new javax.swing.JLabel();
        txtVariedad = new javax.swing.JTextField();
        txtCaracteristicas = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(390, 320));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("Gestión de Variedades");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lbCaracteristicas.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbCaracteristicas.setForeground(new java.awt.Color(0, 0, 0));
        lbCaracteristicas.setText("Características");
        jPanel1.add(lbCaracteristicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        lbVariedad.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbVariedad.setForeground(new java.awt.Color(0, 0, 0));
        lbVariedad.setText("Nombre de la variedad");
        jPanel1.add(lbVariedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        txtVariedad.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtVariedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 330, -1));

        txtCaracteristicas.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtCaracteristicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 330, -1));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 0));
        btnCancelar.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        crud.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String variedad = txtVariedad.getText();
        String caracteristicas = txtCaracteristicas.getText();
        
        if (variedad.isEmpty() || caracteristicas.isEmpty()){
            JOptionPane.showMessageDialog(this, "Verifique ningún dato esté en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            VariedadesDB gestor = new VariedadesDB();
            if (editando){
                gestor.editarVariedad(this.variedad.getId(), variedad, caracteristicas);
            } else {
                gestor.agregarVariedad(variedad, caracteristicas);
            }
        }
        
        crud.cargarDatosTabla();
        crud.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setCrud(CRUDVariedadFruta crud){
        this.crud = crud;
    }
    
    public void setEditando(boolean editando, VariedadFruto variedad){
        if (variedad != null) {
            this.variedad = variedad;
            txtVariedad.setText(variedad.getNombre());
            txtCaracteristicas.setText(variedad.getCaracteristicas());
        }
        this.editando = editando;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POPVariedadFruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POPVariedadFruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POPVariedadFruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POPVariedadFruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POPVariedadFruta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCaracteristicas;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbVariedad;
    private javax.swing.JTextField txtCaracteristicas;
    private javax.swing.JTextField txtVariedad;
    // End of variables declaration//GEN-END:variables
}
